# Generated by Django 2.2.2 on 2019-06-14 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_jurnal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jurnal',
            name='tahun',
            field=models.DateField(blank=True, null=True),
        ),
    ]
