# Generated by Django 2.2.2 on 2019-06-14 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20190614_1926'),
    ]

    operations = [
        migrations.AddField(
            model_name='jurnal',
            name='penerapan',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
